
---
title: Uebungsblatt 03
author: Truong (Hoang Tung Truong, 3080216), Testfran (Minh Kien Nguyen, 3157116), Hamdash
output: pdf_document
header-includes:
   - \usepackage{amssymb}
---

## Aufgabe 1

$F \rightarrow G$ ist unerfüllbar

genau dann wenn für alle passenden Belegungen $\alpha$ gilt $\hat{\alpha}(F \rightarrow G) = 0$

genau dann wenn für alle passenden Belegungen $\alpha$ gilt $\hat{\alpha}(\neg F \lor G) = 0$

genau dann wenn für alle passenden Belegungen $\alpha$ gilt $! \hat{\alpha}(F)$ $|$ $\hat{\alpha}(G) = 0$

genau dann wenn für alle passenden Belegungen $\alpha$ gilt $! \hat{\alpha}(F) = 0$ und $\hat{\alpha}(G) = 0$

genau dann wenn für alle passenden Belegungen $\alpha$ gilt $\hat{\alpha}(F) = 1$ und $\hat{\alpha}(G) = 0$

genau dann wenn für alle passenden Belegungen $\alpha$ gilt $F$ ist allegemeingültig und $G$ ist unerfüllbar


## Aufgabe 2

1. $F_{[G_1/A_1, G_2/A_2]}$

   $= (A_1 \rightarrow A_2) \land A_3 \rightarrow ( \neg (A_1 \lor A_2) \lor \neg (A_1 \rightarrow A_2))$

   $= (A_1 \rightarrow A_2) \land A_3 \rightarrow ( ( \neg A_1 \land \neg A_2) \lor (A_1 \land \neg A_2))$

   $= (A_1 \rightarrow A_2) \land A_3 \rightarrow \neg A_2$

   $= \neg ((\neg A_1 \lor A_2) \land A_3) \lor \neg A_2$

   $= (A_1 \land \neg A_2 \lor \neg A_3) \lor \neg A_2$

   $= (A_1 \land \neg A_2) \lor \neg A_2 \lor \neg A_3$

   $= \neg A_2 \lor \neg A_3$

2. $\alpha (G_1) = (A_1 \rightarrow A_2)_{[1/A_1, 0/A_2]} = 1 \rightarrow 0 = 0$

   $\alpha (G_2) = (A_1 \lor A_2)_{[1/A_1, 0/A_2]} = 1 \lor 0 = 1$

   $\alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} = [A_1 \mapsto 0, A_2 \mapsto 1, A_3 \mapsto 1]$

3. $\alpha (F_{[G_1/A_1, G_2/A_2]})$

   $= \alpha (\neg A_2 \lor \neg A_3)$

   $= ! \alpha (A_2)$ $|$ $! \alpha (A_3)$

   $= ! 0$ $|$ $! 1 = 1$ $|$ $0 = 1$

4. $(\alpha_{[A_1 \mapsto \alpha (G_1)]})_{[A_2 \mapsto \alpha (G_2)]}$

   $= (\alpha_{[A_1 \mapsto 0]})_{[A_2 \mapsto 1]}$

   $= \alpha_{[A_1 \mapsto 0, A_2 \mapsto 1]}$

   $= [A_1 \mapsto 0, A_2 \mapsto 1, A_3 \mapsto 1]$

## Aufgabe 3
1. Definition von $F_{[G_1/A_1, G_2/A_2]}$ (Annahme: $A_1, A_2$ seien atomare Formeln)

- Ist $F$ eine atomare Formel:

  Falls $F = A_1$ dann $F_{[G_1/A_1, G_2/A_2]} := G_1$

  Falls $F = A_2$ dann $F_{[G_1/A_1, G_2/A_2]} := G_2$

  Falls $F \neq A_1$ und $F \neq A_2$ dann $F_{[G_1/A_1, G_2/A_2]} := F$

- Ist $F = \neg F_1$, dann $F_{[G_1/A_1, G_2/A_2]} := \neg F_{1[G_1/A_1,G_2/A_2]}$

- Ist $F = F_1 \odot F_2$ eine zusammengesetzte Formel $(\odot \in \{\land, \lor, \rightarrow, \leftrightarrow, ...\})$ dann

  $F_{[G_1/A_1, G_2/A_2]} = (F_1 \odot F_2)_{[G_1/A_1, G_2/A_2]}$

  $:= F_{1[G_1/A_1, G_2/A_2]} \odot F_{2[G_1/A_1, G_2/A_2]}$

2. Beweis (Annahme: $A_1, A_2$ seien atomare Formeln)

- Ist $F$ eine atomare Formel

  Falls $F = A_1$ dann

  $\alpha (F_{[G_1/A_1, G_2/A_2]}) = \alpha (G_1)$

  $= \alpha_{[A_1 \mapsto \alpha (G_1)]}(A_1)$

  $= \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F)$

  Falls $F = A_2$ dann

  $\alpha (F_{[G_1/A_1, G_2/A_2]})= \alpha (G_2)$

  $= \alpha_{[A_2 \mapsto \alpha (G_2)]}(A_2)$

  $= \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F)$

  Falls $F \neq A_1$ und $F \neq A_2$ dann

  $\alpha (F_{[G_1/A_1, G_2/A_2]}) = \alpha (F)$

  $= \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F)$

- Ist $F = \neg F_1$, dann mit der Annahme **(1)**: $\alpha(F_{1[G_1/A_1, G_2/A_2]}) = \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F_1)$ gilt:

  $\alpha (F_{[G_1/A_1, G_2/A_2]}) = ! \alpha (F_{1[G_1/A_1, G_2/A_2]})$

  $= ! \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto (G_2)]} (F_1)$

  $= \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto (G_2)]} (\neg F_1)$

  $= \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto (G_2)]} (F)$

- Ist $F = F_1 \odot F_2$ eine zusammengesetzte Formeln $(\odot \in \{\land, \lor, \rightarrow, \leftrightarrow, ...\})$ und mit der Annahme $\alpha (F_{2[G_1/A_1, G_2/A_2]}) = \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F_2)$ und **(1)** gilt

  $\alpha (F_{[G_1/A_1, G_2/A_2]}) = \alpha (F_{1[G_1/A_1, G_2/A_2]} \odot F_{2[G_1/A_1, G_2/A_2]})$

  $= \alpha (F_{1[G_1/A_1, G_2/A_2]}) \odot \alpha (F_{1[G_1/A_1, G_2/A_2]})$

  $= \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F_1) \odot \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F_2)$

  $= \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F_1 \odot F_2) = \alpha_{[A_1 \mapsto \alpha (G_1), A_2 \mapsto \alpha (G_2)]} (F)$ $\Box$

## Aufgabe 4
a. $ite(x,y,z) = (x \land y) \lor (\neg x \land z)$

- $\neg$ Junktor: $\neg x = ite(x, \bot, \top) = (x \land \bot) \lor (\neg x \land \top) = (\bot \lor \neg x) = \neg x$

- $\lor$ Junktor: $x \lor y = \top \land (x \lor y)$

  $= (x \lor \neg x) \land (x \lor y)$

  $= x \lor (\neg x \land y)$

  $= (x \land \top) \lor (\neg x \land y)$

  $= ite(x,\top,y)$

- $\rightarrow$ Junktor: $x \rightarrow y = \neg x \lor y$

  $= \top \land (y \lor \neg x)$

  $= (x \lor \neg x) \land (y \lor \neg x)$

  $= (x \land y) \lor \neg x$

  $= (x \land y) \lor (\neg x \land \top)$

  $= ite(x,y,\top)$

- $\leftrightarrow$ Junktor: $x \leftrightarrow y = (x \land y) \lor (\neg x \land \neg y)$

  $= ite(x,y,ite(y,\bot,\top))$
b. Behauptung: $\lor, \land$ sind zweistellige monotone boolesche Funktionen

Beweis (durch Wahrheitstabelle): $\forall a_1, a_2, b_1, b_2 \in \mathbb{B}: \forall i \in \{1,2\}:$ $a_i \leq b_i \Rightarrow f(a_1,a_2) \leq f(b_1, b_2)$, also

| $a_1$ | $a_2$ | $b_1$ | $b_2$ | $a_1 \lor a_2$ | $b_1 \lor b_2$ |
|---|----|----|----|------|----|
| 0 | 0  | 0  | 0  |  0   | 0  |
| 0 | 0  | 1  | 0  |  0   | 1  |
| 1 | 0  | 1  | 0  |  1   | 1  |
| 0 | 0  | 0  | 1  |  0   | 1  |
| 0 | 0  | 1  | 1  |  0   | 1  |
| 1 | 0  | 1  | 1  |  1   | 1  |
| 0 | 1  | 0  | 1  |  1   | 1  |
| 0 | 1  | 1  | 1  |  1   | 1  |
| 1 | 1  | 1  | 1  |  1   | 1  |

Aus der Eigenschaft, dass die Komposition von monotonen Funktionen wieder eine monotone Funktionen ist, können wir schließen, dass die Komposition von $\lor, \land, \bot, \top$ wieder eine monotone Funktion ist **(1)**

Behauptung : $\neg$ ist keine monotone boolesche Funktion **(2)**

Beweis: (durch Wahrheitstabelle) Für $\neg$ gilt $\forall a_1, b_1 \in \mathbb{B}: a_1 \leq b_1 \Rightarrow f(a_1) \geq f(a_2)$

| $a_1$ | $b_1$ | $\neg a_1$ | $\neg b_1$ |
|-|-|-|-|
|0|0|1|1|
|0|1|1|0|
|1|1|0|0|

(1) (2) $\Rightarrow$ Aus $\{\lor, \land, \bot, \top \}$ können wir $\neg$ nicht erreichen.

Also $\{\lor, \land, \bot, \top \}$ ist keine ausreichende Menge von Junktoren
