
---
title: Uebungsblatt 05
author: Truong (Hoang Tung Truong, 3080216), Testfran (Minh Kien Nguyen, 3157116), Hamdash
output: pdf_document
header-includes:
   - \usepackage{amssymb}
---

## Aufgabe 1
a. Seien $a = \{L_1, L_2, A_1, ... , A_n\}$ , $k' = \{\neg L_1, \neg L_2, B_1, ..., B_mA\}$ ($A_1, ..., A_n,B_1,...,B_n$ sind Literalen) V-Klauseln -> \\lor

Eine resolvente $R$ von $k$ und $k'$ enthält stets darin die Literalen $L_i, \neg L_i$ wobei $i \in \{1,2\}$

Da $L_i \lor \neg L_i tripleequal T$ und $R$ eine V-Klausel ist, folgt daraus, $R$ ist stets allgemeingultig **(1)**

Resolventmethode soll die Nichterfülltbarkeit zeigen. Die Ausgangformel $F = k \land k'$  ist nicht erfüllbar, falls leere Kualsel erzeugt in der Resolventmethode wird. **(2)**

Aus **(1)** und **(2)** $\Rightarrow$ Dies Resolventmethode braucht nie $k$ und $k'$ zu resolvieren, dann es ist nutzlos $\Box$

b. Nein, man kann $k$ oder $k'$ nicht enthält

$F = \{k,k'\}$ erfüllt genau dann wenn jede Klausel $k,k'$ erfüllt. Wenn man $k$ oder $k'$ entfernt, dann ändert sich die Erfüllbarkeit von F.

Gegenbeispiel: Wenn man $k$ entfernt, sei $F'$ die entstandene Formel ($F' = k'$). Für die Belegung $\alpha$ mit $\alpha(A_1) = ... = \alpha(A_n) = \alpha(L_1) = \alpha(L_2) =0$ gilt $\alpha(F') = \alpha(K') =1$, aber $\alpha(F) =0$, d.h $F'$ erfüllt, aber die ursprüngliche Formel $F$ erfüllt nicht.

## Aufgabe 2
$M = \{k_1, k_2,...,k_n\}$ erfüllt, wenn jede Klauseln $k_1,k_2,...,k_n$ erfüllt. Da $k_2$ eine V-Klausel ist und $k_1 k_2$ subsummiert, gilt es, wenn $k_1$ erfüllt, dann erfüllt auch $k_2$. Also $M$ erfüllt wenn $k_1,k_2,...,k_n$ erfüllen. D.h man kann $k_2$ aus $M$ ertfernen, ohne die Erfüllbarkeit von $M$ zu verändern.


## Aufgabe 5

Behauptung: $\mathcal{F} = \{F_1, F_2, F_3, ... \}$ ist erfüllbar genau dann wenn $\forall n \geq 1: (\land^{n}_{i=1} F_i)$ ist erfüllbar.

"$\Rightarrow$": $\mathcal{F} = \{F_1, F_2, F_3, ... \}$ ist erfüllbar

$\Rightarrow \mathcal{F}$ besitzt ein Modell $\alpha$ ($\alpha \vDash \mathcal{F}$)

$\Rightarrow \forall n \geq 1: \alpha(F_n) =1$ ($\alpha \vDash F_n \forall n \geq 1$)

$\Rightarrow \forall n \geq 1: \alpha(\land^{n}_{i=1} F_i) =1$

$\Rightarrow \forall n \geq 1: \alpha(\land^{n}_{i=1} F_i)$ hat ein Modell $\alpha$, ist also erfüllbar

"$\Leftarrow$" $\forall n \geq 1: \alpha(\land^{n}_{i=1} F_i)$ ist erfüllbar

$\Rightarrow \forall n \geq1: \exists \alpha_n: \alpha_n(\land^{n}_{i=1} F_i) = 1$ **(\*)**

  Für $n=1$: $\exists \alpha_1 (F_1) =1 \Rightarrow {F_1}$ ist erfüllbar

  Für $n=2$: $\exists \alpha_2 (F_1 \land F_2) =1\Rightarrow \alpha_2 (F_2) =1 \Rightarrow \{F_1\}, \{F_2\}, \{F_1, F_2\}$ ist erfüllbar

  Für $n=3$: $\exists \alpha_3 (F_1 \land F_2 \land F_3) =1$

$\Rightarrow \alpha_3(F_3) =1$

$\Rightarrow \alpha_3(F_1 \land F_3) =1$

$\Rightarrow \alpha_3(F_2 \land F_3) =1$

Allgemein gilt es:

Sei $F_k = {F_1, F_2, F_3, ... , F_k}$ ($k \in \mathbb{N}$)

Für $n=k$: $\exists \alpha_k$: $\alpha_k (\land^{k}_{i=1} F_i) =1$,

$\Rightarrow \forall f \in \mathcal{P}(F_k)$ (Potenzmenge von $F_k$) gilt $\alpha_k(f) -1$ (Jede endliche Teilmenge von $F_k$ ist erfüllbar)

D.h aus **(\*)** folgt: Jede endliche Teilmenge von $\mathcal{F}$ ist erfüllbar.

nach dem Kompahtheissatz $\Rightarrow \mathcal{F}$ ist erfüllbar.
